import React from 'react';
import { X, Calendar, Plus, Check, Clock, Building, User, Tag, ArrowRight } from 'lucide-react';
import { LembreteItem } from '../../types/lembretes';
import { useNavigation } from '../../context/NavigationContext';

interface DetalhesDiaCalendarioModalProps {
  isOpen: boolean;
  onClose: () => void;
  dateStr: string; // YYYY-MM-DD
  events: LembreteItem[];
  onAddNewEvent: (dateStr: string) => void;
  onToggleStatus: (id: string) => void;
  onSnooze: (id: string) => void;
}

export const DetalhesDiaCalendarioModal: React.FC<DetalhesDiaCalendarioModalProps> = ({
  isOpen,
  onClose,
  dateStr,
  events,
  onAddNewEvent,
  onToggleStatus,
  onSnooze
}) => {
  const { navigateTo } = useNavigation();

  if (!isOpen) return null;

  const formattedDate = (() => {
    try {
      const [year, month, day] = dateStr.split('-');
      const d = new Date(parseInt(year, 10), parseInt(month, 10) - 1, parseInt(day, 10));
      return d.toLocaleDateString('pt-BR', {
        weekday: 'long',
        day: 'numeric',
        month: 'long',
        year: 'numeric'
      });
    } catch {
      return dateStr;
    }
  })();

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/60 backdrop-blur-xs animate-in fade-in duration-150">
      <div className="bg-white w-full max-w-lg rounded-2xl shadow-2xl border border-slate-200 overflow-hidden flex flex-col max-h-[85vh]">
        {/* Header */}
        <div className="px-5 py-4 bg-gradient-to-r from-slate-900 to-blue-950 text-white flex items-center justify-between shrink-0">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-blue-600/30 border border-blue-400/40 flex items-center justify-center text-blue-300">
              <Calendar className="w-4 h-4" />
            </div>
            <div>
              <h2 className="text-sm font-bold capitalize">
                {formattedDate}
              </h2>
              <p className="text-[11px] text-slate-300">
                {events.length} evento{events.length === 1 ? '' : 's'} agendado{events.length === 1 ? '' : 's'} neste dia
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-lg text-slate-400 hover:text-white hover:bg-white/10 transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content list */}
        <div className="p-5 overflow-y-auto space-y-3 flex-1 text-xs">
          {events.length === 0 ? (
            <div className="text-center py-8 text-slate-500 space-y-2">
              <Calendar className="w-8 h-8 mx-auto text-slate-300 stroke-1" />
              <p className="text-xs font-medium">Nenhum evento registrado para este dia.</p>
              <button
                onClick={() => {
                  onClose();
                  onAddNewEvent(dateStr);
                }}
                className="mt-2 px-3 py-1.5 rounded-xl bg-blue-50 text-blue-700 font-bold border border-blue-200 hover:bg-blue-100 cursor-pointer inline-flex items-center gap-1"
              >
                <Plus className="w-3.5 h-3.5" />
                <span>Adicionar Lembrete Neste Dia</span>
              </button>
            </div>
          ) : (
            events.map((ev) => {
              const isCompleted = ev.status === 'CONCLUIDO';
              return (
                <div
                  key={ev.id}
                  className={`p-3.5 rounded-xl border transition-all ${
                    isCompleted
                      ? 'bg-slate-50 border-slate-200 opacity-60'
                      : ev.priority === 'URGENTE'
                      ? 'bg-red-50/40 border-red-200'
                      : 'bg-white border-slate-200 shadow-2xs hover:border-blue-300'
                  }`}
                >
                  <div className="flex items-start justify-between gap-2">
                    <div className="space-y-1 min-w-0">
                      <div className="flex items-center gap-1.5 flex-wrap">
                        <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                          ev.priority === 'URGENTE' ? 'bg-red-100 text-red-800' : 'bg-slate-100 text-slate-700'
                        }`}>
                          {ev.priority}
                        </span>
                        {ev.time && (
                          <span className="text-[10px] font-mono text-slate-500 flex items-center gap-0.5">
                            <Clock className="w-3 h-3 text-slate-400" />
                            {ev.time}
                          </span>
                        )}
                        {ev.isAutoGenerated && (
                          <span className="px-1.5 py-0.2 rounded text-[9px] font-semibold bg-purple-50 text-purple-700 border border-purple-200">
                            Auto
                          </span>
                        )}
                      </div>

                      <h4 className={`text-xs font-bold ${isCompleted ? 'line-through text-slate-500' : 'text-slate-900'}`}>
                        {ev.title}
                      </h4>

                      <p className="text-[11px] text-slate-600 leading-relaxed">
                        {ev.description}
                      </p>

                      {ev.collaboratorName && (
                        <div className="flex items-center gap-1 text-[10px] text-slate-500 pt-0.5">
                          <User className="w-3 h-3 text-blue-600" />
                          <span>{ev.collaboratorName} ({ev.poloNome || 'SCL'})</span>
                        </div>
                      )}
                    </div>

                    {/* Action buttons */}
                    <div className="flex flex-col items-end gap-1.5 shrink-0">
                      <button
                        onClick={() => onToggleStatus(ev.id)}
                        className={`p-1.5 rounded-lg border cursor-pointer transition-colors ${
                          isCompleted
                            ? 'bg-emerald-600 text-white border-emerald-600'
                            : 'bg-white hover:bg-emerald-50 text-slate-500 hover:text-emerald-700 border-slate-200'
                        }`}
                        title={isCompleted ? 'Marcar como Pendente' : 'Marcar como Concluído'}
                      >
                        <Check className="w-3.5 h-3.5" />
                      </button>

                      {ev.actionModule && !isCompleted && (
                        <button
                          onClick={() => {
                            navigateTo(ev.actionModule!);
                            onClose();
                          }}
                          className="p-1.5 rounded-lg bg-blue-50 hover:bg-blue-100 text-blue-700 border border-blue-200 cursor-pointer"
                          title="Ir para módulo"
                        >
                          <ArrowRight className="w-3.5 h-3.5" />
                        </button>
                      )}
                    </div>
                  </div>
                </div>
              );
            })
          )}
        </div>

        {/* Footer */}
        <div className="px-5 py-3 bg-slate-50 border-t border-slate-200 flex items-center justify-between">
          <button
            onClick={() => {
              onClose();
              onAddNewEvent(dateStr);
            }}
            className="px-3.5 py-1.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold flex items-center gap-1 cursor-pointer transition-colors shadow-2xs"
          >
            <Plus className="w-3.5 h-3.5" />
            <span>Novo Lembrete para {dateStr.split('-').reverse().slice(0, 2).join('/')}</span>
          </button>

          <button
            onClick={onClose}
            className="px-3 py-1.5 rounded-xl border border-slate-200 text-slate-700 hover:bg-slate-100 font-semibold text-xs cursor-pointer"
          >
            Fechar
          </button>
        </div>
      </div>
    </div>
  );
};
