import React, { useState } from 'react';
import { X, Calendar, Clock, AlertCircle, Building, User, Tag, Check, Bell } from 'lucide-react';
import { LembreteItem, LembreteCategory, LembretePriority } from '../../types/lembretes';
import { useAuth } from '../../context/AuthContext';
import { getStoredCollaborators } from '../../utils/collaboratorsStorage';

interface NovoLembreteModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (data: Omit<LembreteItem, 'id' | 'createdAt' | 'isAutoGenerated' | 'sourceType'>) => void;
  initialDate?: string;
  editingItem?: LembreteItem | null;
}

const CATEGORY_OPTIONS: { id: LembreteCategory; label: string; icon: string; color: string }[] = [
  { id: 'PERSONALIZADO', label: 'Lembrete Geral / Tarefa', icon: '📝', color: 'bg-slate-100 text-slate-800 border-slate-300' },
  { id: 'EXPERIENCIA', label: 'Contrato & Experiência CLT', icon: '📋', color: 'bg-amber-100 text-amber-800 border-amber-300' },
  { id: 'FOLHA_DP', label: 'Rotina de Folha / DP', icon: '💼', color: 'bg-blue-100 text-blue-800 border-blue-300' },
  { id: 'ASO_SST', label: 'Saúde & Segurança (ASO / NR / EPI)', icon: '🩺', color: 'bg-emerald-100 text-emerald-800 border-emerald-300' },
  { id: 'FERIAS', label: 'Férias & Afastamentos', icon: '🏖️', color: 'bg-indigo-100 text-indigo-800 border-indigo-300' },
  { id: 'ANIVERSARIO', label: 'Aniversário / Marco Own It', icon: '🎂', color: 'bg-pink-100 text-pink-800 border-pink-300' },
  { id: 'CONTRATO', label: 'Contrato PJ / Estágio / Prazo', icon: '📑', color: 'bg-purple-100 text-purple-800 border-purple-300' }
];

export const NovoLembreteModal: React.FC<NovoLembreteModalProps> = ({
  isOpen,
  onClose,
  onSave,
  initialDate,
  editingItem
}) => {
  const { branches } = useAuth();
  const colaboradores = getStoredCollaborators();

  const todayStr = new Date().toISOString().split('T')[0];

  const [title, setTitle] = useState(editingItem?.title || '');
  const [description, setDescription] = useState(editingItem?.description || '');
  const [date, setDate] = useState(editingItem?.date || initialDate || todayStr);
  const [time, setTime] = useState(editingItem?.time || '09:00');
  const [category, setCategory] = useState<LembreteCategory>(editingItem?.category || 'PERSONALIZADO');
  const [priority, setPriority] = useState<LembretePriority>(editingItem?.priority || 'ALTA');
  const [poloId, setPoloId] = useState(editingItem?.poloId || '');
  const [collaboratorId, setCollaboratorId] = useState(editingItem?.collaboratorId || '');
  const [alertDaysBefore, setAlertDaysBefore] = useState<number>(editingItem?.alertDaysBefore ?? 3);
  const [recurrence, setRecurrence] = useState<'NENHUMA' | 'MENSAL' | 'ANUAL'>(editingItem?.recurrence || 'NENHUMA');

  if (!isOpen) return null;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim() || !date) return;

    const selectedPolo = branches.find(b => b.id === poloId);
    const selectedColab = colaboradores.find(c => c.id === collaboratorId);
    const colabName = selectedColab ? (selectedColab.fullName || selectedColab.preferredName) : undefined;

    onSave({
      title: title.trim(),
      description: description.trim(),
      date,
      time: time || undefined,
      category,
      priority,
      status: editingItem?.status || 'PENDENTE',
      poloId: poloId || undefined,
      poloNome: selectedPolo?.name || undefined,
      collaboratorId: collaboratorId || undefined,
      collaboratorName: colabName,
      collaboratorRole: selectedColab?.positionTitle || undefined,
      alertDaysBefore,
      recurrence
    });

    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/60 backdrop-blur-xs animate-in fade-in duration-150">
      <div className="bg-white w-full max-w-xl rounded-2xl shadow-2xl border border-slate-200 overflow-hidden flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="px-6 py-4.5 bg-gradient-to-r from-slate-900 via-slate-850 to-blue-950 text-white flex items-center justify-between shrink-0">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-blue-600/30 border border-blue-400/40 flex items-center justify-center text-blue-300">
              <Bell className="w-4 h-4" />
            </div>
            <div>
              <h2 className="text-sm font-bold tracking-tight">
                {editingItem ? 'Editar Lembrete' : 'Novo Lembrete & Alerta'}
              </h2>
              <p className="text-[11px] text-slate-300">
                Agendamento de prazos, rotinas trabalhistas e notificações automáticas
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-lg text-slate-400 hover:text-white hover:bg-white/10 transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Form Body */}
        <form onSubmit={handleSubmit} className="p-6 overflow-y-auto space-y-4 text-xs">
          
          {/* Título */}
          <div className="space-y-1.5">
            <label className="block text-xs font-bold text-slate-800">
              Título do Lembrete <span className="text-red-500">*</span>
            </label>
            <input
              type="text"
              required
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="Ex: Vencimento da 2ª parcela do 13º / Renovar ASO Operacional"
              className="w-full px-3.5 py-2.5 rounded-xl border border-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 text-xs font-medium"
            />
          </div>

          {/* Categoria */}
          <div className="space-y-1.5">
            <label className="block text-xs font-bold text-slate-800">
              Categoria do Evento
            </label>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
              {CATEGORY_OPTIONS.map((cat) => (
                <button
                  type="button"
                  key={cat.id}
                  onClick={() => setCategory(cat.id)}
                  className={`p-2 rounded-xl border text-left flex items-center gap-2 transition-all cursor-pointer ${
                    category === cat.id
                      ? 'border-blue-600 bg-blue-50/70 text-blue-950 font-bold shadow-2xs'
                      : 'border-slate-200 bg-slate-50/50 hover:bg-slate-100 text-slate-700'
                  }`}
                >
                  <span className="text-base">{cat.icon}</span>
                  <span className="text-[11px] leading-tight truncate">{cat.label}</span>
                </button>
              ))}
            </div>
          </div>

          {/* Data, Horário e Prioridade */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <div className="space-y-1.5">
              <label className="block text-xs font-bold text-slate-800 flex items-center gap-1">
                <Calendar className="w-3.5 h-3.5 text-slate-500" />
                Data de Vencimento <span className="text-red-500">*</span>
              </label>
              <input
                type="date"
                required
                value={date}
                onChange={(e) => setDate(e.target.value)}
                className="w-full px-3 py-2 rounded-xl border border-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 text-xs font-medium"
              />
            </div>

            <div className="space-y-1.5">
              <label className="block text-xs font-bold text-slate-800 flex items-center gap-1">
                <Clock className="w-3.5 h-3.5 text-slate-500" />
                Horário (Opcional)
              </label>
              <input
                type="time"
                value={time}
                onChange={(e) => setTime(e.target.value)}
                className="w-full px-3 py-2 rounded-xl border border-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 text-xs font-medium"
              />
            </div>

            <div className="space-y-1.5">
              <label className="block text-xs font-bold text-slate-800 flex items-center gap-1">
                <AlertCircle className="w-3.5 h-3.5 text-slate-500" />
                Nível de Prioridade
              </label>
              <select
                value={priority}
                onChange={(e) => setPriority(e.target.value as LembretePriority)}
                className="w-full px-3 py-2 rounded-xl border border-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 text-xs font-medium bg-white"
              >
                <option value="URGENTE">🔴 Urgente (Crítico)</option>
                <option value="ALTA">🟠 Alta Prioridade</option>
                <option value="MEDIA">🔵 Média Prioridade</option>
                <option value="BAIXA">⚪ Normal / Informativo</option>
              </select>
            </div>
          </div>

          {/* Vínculo: Polo e Colaborador */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-1">
            <div className="space-y-1.5">
              <label className="block text-xs font-bold text-slate-800 flex items-center gap-1">
                <Building className="w-3.5 h-3.5 text-slate-500" />
                Vincular ao Polo / Operação
              </label>
              <select
                value={poloId}
                onChange={(e) => setPoloId(e.target.value)}
                className="w-full px-3 py-2 rounded-xl border border-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 text-xs font-medium bg-white"
              >
                <option value="">Geral / Todas as Operações</option>
                {branches.map((b) => (
                  <option key={b.id} value={b.id}>
                    {b.name} ({b.code})
                  </option>
                ))}
              </select>
            </div>

            <div className="space-y-1.5">
              <label className="block text-xs font-bold text-slate-800 flex items-center gap-1">
                <User className="w-3.5 h-3.5 text-slate-500" />
                Vincular Colaborador
              </label>
              <select
                value={collaboratorId}
                onChange={(e) => {
                  setCollaboratorId(e.target.value);
                  const selected = colaboradores.find(c => c.id === e.target.value);
                  if (selected && !poloId) {
                    setPoloId(selected.branchId);
                  }
                }}
                className="w-full px-3 py-2 rounded-xl border border-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 text-xs font-medium bg-white"
              >
                <option value="">Nenhum (Lembrete Institucional)</option>
                {colaboradores.map((c) => (
                  <option key={c.id} value={c.id}>
                    {c.fullName || c.preferredName} — {c.positionTitle} ({c.branchName})
                  </option>
                ))}
              </select>
            </div>
          </div>

          {/* Configuração do Pop-up e Repetição */}
          <div className="p-3.5 rounded-xl border border-blue-100 bg-blue-50/40 space-y-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-1.5 text-xs font-bold text-blue-950">
                <Bell className="w-4 h-4 text-blue-600" />
                <span>Disparo do Pop-up Inteligente</span>
              </div>
              <span className="text-[10px] text-blue-700 font-semibold">
                Alerta automático na tela
              </span>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
              <div>
                <label className="block text-[11px] font-semibold text-slate-700 mb-1">
                  Disparar pop-up de alerta com antecedência de:
                </label>
                <select
                  value={alertDaysBefore}
                  onChange={(e) => setAlertDaysBefore(parseInt(e.target.value, 10))}
                  className="w-full px-2.5 py-1.5 rounded-lg border border-slate-300 text-xs font-medium bg-white"
                >
                  <option value={0}>No exato dia do vencimento</option>
                  <option value={1}>1 dia antes</option>
                  <option value={3}>3 dias antes (Recomendado)</option>
                  <option value={5}>5 dias antes</option>
                  <option value={7}>7 dias antes (1 semana)</option>
                  <option value={15}>15 dias antes (Férias/ASO)</option>
                  <option value={30}>30 dias antes (Dobra de Férias)</option>
                </select>
              </div>

              <div>
                <label className="block text-[11px] font-semibold text-slate-700 mb-1">
                  Repetição periódica:
                </label>
                <select
                  value={recurrence}
                  onChange={(e) => setRecurrence(e.target.value as 'NENHUMA' | 'MENSAL' | 'ANUAL')}
                  className="w-full px-2.5 py-1.5 rounded-lg border border-slate-300 text-xs font-medium bg-white"
                >
                  <option value="NENHUMA">Não repete (Evento único)</option>
                  <option value="MENSAL">Mensal (ex: todo dia 25)</option>
                  <option value="ANUAL">Anual (ex: aniversários)</option>
                </select>
              </div>
            </div>
          </div>

          {/* Descrição / Observações */}
          <div className="space-y-1.5">
            <label className="block text-xs font-bold text-slate-800">
              Observações & Detalhes do Evento
            </label>
            <textarea
              rows={3}
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Instruções adicionais, contatos de clínicas, procedimentos de DP ou links relevantes..."
              className="w-full px-3 py-2 rounded-xl border border-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 text-xs"
            />
          </div>

          {/* Footer Actions */}
          <div className="pt-3 border-t border-slate-100 flex items-center justify-end gap-2.5">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 rounded-xl border border-slate-200 text-slate-700 hover:bg-slate-100 font-semibold text-xs cursor-pointer transition-colors"
            >
              Cancelar
            </button>
            <button
              type="submit"
              className="px-5 py-2 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs flex items-center gap-1.5 shadow-sm transition-colors cursor-pointer"
            >
              <Check className="w-4 h-4" />
              <span>{editingItem ? 'Salvar Alterações' : 'Criar Lembrete'}</span>
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
