import { MainModuleId } from './navigation';

export type LembreteCategory = 
  | 'EXPERIENCIA'       // Vencimento de Experiência 45d / 90d CLT
  | 'FOLHA_DP'          // Fechamento dia 25, Pagamento 5º dia útil, Adiantamento dia 20, 13º Salário
  | 'ASO_SST'           // Exames Ocupacionais ASO, NRs (NR-10, NR-35), Validade de EPI
  | 'FERIAS'            // Vencimento período concessivo, início de gozo
  | 'ANIVERSARIO'       // Aniversário de nascimento e Aniversário de empresa (Own It)
  | 'CONTRATO'          // Contratos com prazo determinado, estágio, aprendiz, RPA
  | 'PERSONALIZADO';    // Lembrete manual criado pelo usuário

export type LembretePriority = 'URGENTE' | 'ALTA' | 'MEDIA' | 'BAIXA';

export type LembreteStatus = 'PENDENTE' | 'CONCLUIDO' | 'ADIADO';

export type LembreteSourceType = 
  | 'EXPERIENCIA_45'
  | 'EXPERIENCIA_90'
  | 'FECHAMENTO_FOLHA'
  | 'PAGAMENTO_SALARIO'
  | 'ADIANTAMENTO'
  | 'DECIMO_TERCEIRO'
  | 'ASO'
  | 'NR_TREINAMENTO'
  | 'EPI_VALIDADE'
  | 'FERIAS_DOBRO'
  | 'FERIAS_INICIO'
  | 'ANIVERSARIO_NATALICIO'
  | 'ANIVERSARIO_EMPRESA'
  | 'CONTRATO_FIM'
  | 'CUSTOM';

export interface LembreteItem {
  id: string;
  title: string;
  description: string;
  date: string; // YYYY-MM-DD
  time?: string; // HH:mm
  category: LembreteCategory;
  priority: LembretePriority;
  status: LembreteStatus;
  poloId?: string;
  poloNome?: string;
  collaboratorId?: string;
  collaboratorName?: string;
  collaboratorRole?: string;
  isAutoGenerated: boolean;
  sourceType: LembreteSourceType;
  recurrence?: 'NENHUMA' | 'MENSAL' | 'ANUAL';
  alertDaysBefore: number; // Disparar popup com X dias de antecedência (ex: 0, 1, 3, 7, 15)
  actionLabel?: string;
  actionModule?: MainModuleId;
  actionPayload?: Record<string, unknown>;
  createdAt: string;
  completedAt?: string;
  snoozedUntil?: string; // YYYY-MM-DD
}

export interface LembretesFilterState {
  category: string; // 'ALL' or specific category
  priority: string; // 'ALL' or specific priority
  status: string;   // 'ALL' | 'PENDENTE' | 'CONCLUIDO' | 'ATRASADO'
  poloId: string;   // 'ALL' or specific polo ID
  searchTerm: string;
  viewMode: 'calendar' | 'timeline' | 'agenda';
}
