import { useState, useEffect, useCallback } from 'react';
import { LembreteItem, LembreteCategory, LembretePriority } from '../types/lembretes';
import { getStoredCollaborators } from './collaboratorsStorage';
import { getStoredAdmissoes } from './admissaoStorage';
import { calcularDataTerminoExperiencia } from './documentosOnboardingHelper';

export const LEMBRETES_CUSTOM_KEY = 'scl_lembretes_custom_v1';
export const LEMBRETES_STATUS_KEY = 'scl_lembretes_status_v1';
export const LEMBRETES_POPUP_DISMISSED_KEY = 'scl_lembretes_popup_dismissed_v1';
export const LEMBRETES_UPDATE_EVENT = 'scl_lembretes_updated';

interface StoredStatusOverride {
  status: 'PENDENTE' | 'CONCLUIDO' | 'ADIADO';
  completedAt?: string;
  snoozedUntil?: string;
}

function safeGetJSON<T>(key: string, fallback: T): T {
  if (typeof window === 'undefined') return fallback;
  try {
    const raw = localStorage.getItem(key);
    return raw ? JSON.parse(raw) : fallback;
  } catch {
    return fallback;
  }
}

function safeSetJSON(key: string, value: unknown): void {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(key, JSON.stringify(value));
  } catch (err) {
    console.warn(`[LembretesStorage] Erro ao salvar chave ${key}:`, err);
  }
}

/**
 * Calcula a diferença em dias entre duas datas (YYYY-MM-DD)
 */
export function getDaysDifference(targetDateStr: string, baseDateStr?: string): number {
  try {
    const now = baseDateStr ? new Date(baseDateStr + 'T00:00:00') : new Date();
    const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    const target = new Date(targetDateStr + 'T00:00:00');
    const diffTime = target.getTime() - today.getTime();
    return Math.ceil(diffTime / (1000 * 60 * 60 * 24));
  } catch {
    return 0;
  }
}

/**
 * Gera uma lista de eventos e lembretes automáticos a partir do ecossistema SCL
 */
export function generateAutoLembretes(): LembreteItem[] {
  const autoList: LembreteItem[] = [];
  const currentYear = new Date().getFullYear();

  // 1. Processos de Admissão Digital
  try {
    const admissoes = getStoredAdmissoes();
    admissoes.forEach((adm) => {
      const p1Date = adm.dataInicioAtividades;
      const p2Date = calcularDataTerminoExperiencia(p1Date, 90);
      const p1StatusAssinado = adm.disparosOnboarding?.primeiroDiaOnboarding?.status === 'CONCLUIDO' || adm.disparosOnboarding?.primeiroDiaOnboarding?.status === 'DISPARADO_AUTOMATICO';
      const p2StatusAssinado = adm.disparosOnboarding?.finalPeriodoExperiencia?.status === 'CONCLUIDO' || adm.disparosOnboarding?.finalPeriodoExperiencia?.status === 'DISPARADO_AUTOMATICO';

      // Disparo 1º Dia de Onboarding
      autoList.push({
        id: `auto-adm-p1-${adm.id}`,
        title: `1º Dia Onboarding: ${adm.candidatoNome}`,
        description: `Disparo automático do pacote inicial (Contrato de Experiência, Termo VT e Manual de Conduta). Polo: ${adm.poloNome}.`,
        date: p1Date,
        category: 'EXPERIENCIA',
        priority: 'ALTA',
        status: p1StatusAssinado ? 'CONCLUIDO' : 'PENDENTE',
        poloId: adm.poloId,
        poloNome: adm.poloNome,
        collaboratorName: adm.candidatoNome,
        collaboratorRole: adm.cargo,
        isAutoGenerated: true,
        sourceType: 'EXPERIENCIA_45',
        alertDaysBefore: 3,
        actionLabel: 'Ver Admissão & Disparos',
        actionModule: 'admissao-demissao',
        createdAt: adm.criadoEm || p1Date
      });

      // Término de Experiência 90 dias
      autoList.push({
        id: `auto-adm-p2-${adm.id}`,
        title: `Término de Experiência (90d): ${adm.candidatoNome}`,
        description: `Conclusão do período probatório de 90 dias CLT. Disparar Contrato Definitivo de Efetivação.`,
        date: p2Date,
        category: 'EXPERIENCIA',
        priority: 'URGENTE',
        status: p2StatusAssinado ? 'CONCLUIDO' : 'PENDENTE',
        poloId: adm.poloId,
        poloNome: adm.poloNome,
        collaboratorName: adm.candidatoNome,
        collaboratorRole: adm.cargo,
        isAutoGenerated: true,
        sourceType: 'EXPERIENCIA_90',
        alertDaysBefore: 7,
        actionLabel: 'Disparar Contrato Definitivo',
        actionModule: 'admissao-demissao',
        createdAt: adm.criadoEm || p1Date
      });
    });
  } catch (err) {
    console.warn('[Lembretes] Erro ao carregar admissões:', err);
  }

  // 2. Colaboradores Ativos (ASOs, NRs, Férias, Aniversários, Experiência)
  try {
    const colaboradores = getStoredCollaborators();
    colaboradores.forEach((colab) => {
      const colabName = colab.fullName || colab.preferredName || 'Colaborador';

      // a) ASO Periódico / Exames Médicos
      if (colab.medicalExams && colab.medicalExams.length > 0) {
        colab.medicalExams.forEach((aso) => {
          if (aso.validUntil) {
            autoList.push({
              id: `auto-aso-${colab.id}-${aso.id}`,
              title: `Renovação de ASO (${aso.type}): ${colabName}`,
              description: `Vencimento do ASO Ocupacional realizado na clínica ${aso.clinicName || 'Conveniada'}. Agendar exame periódico.`,
              date: aso.validUntil,
              category: 'ASO_SST',
              priority: 'ALTA',
              status: aso.status === 'EM_DIA' ? 'PENDENTE' : 'PENDENTE',
              poloId: colab.branchId,
              poloNome: colab.branchName,
              collaboratorId: colab.id,
              collaboratorName: colabName,
              collaboratorRole: colab.positionTitle,
              isAutoGenerated: true,
              sourceType: 'ASO',
              alertDaysBefore: 15,
              actionLabel: 'Ver Prontuário de Saúde',
              actionModule: 'gestao-pessoas',
              createdAt: aso.examDate || colab.admissionDate
            });
          }
        });
      }

      // b) Validade de EPIs
      if (colab.epis && colab.epis.length > 0) {
        colab.epis.forEach((epi) => {
          if (epi.expirationDate) {
            autoList.push({
              id: `auto-epi-${colab.id}-${epi.id}`,
              title: `Validade de EPI (${epi.name}): ${colabName}`,
              description: `EPI com CA nº ${epi.caNumber || 'N/A'} atingindo data de validade/troca. Polo ${colab.branchName}.`,
              date: epi.expirationDate,
              category: 'ASO_SST',
              priority: 'MEDIA',
              status: 'PENDENTE',
              poloId: colab.branchId,
              poloNome: colab.branchName,
              collaboratorId: colab.id,
              collaboratorName: colabName,
              collaboratorRole: colab.positionTitle,
              isAutoGenerated: true,
              sourceType: 'EPI_VALIDADE',
              alertDaysBefore: 10,
              actionLabel: 'Ver Ficha de EPI',
              actionModule: 'gestao-pessoas',
              createdAt: epi.deliveryDate || colab.admissionDate
            });
          }
        });
      }

      // c) Férias - Período Concessivo / Risco de Pagar em Dobro
      if (colab.vacationPeriods && colab.vacationPeriods.length > 0) {
        colab.vacationPeriods.forEach((vac) => {
          if (vac.limitConcessionDate && (vac.status === 'DISPONIVEL' || vac.status === 'VENCENDO')) {
            autoList.push({
              id: `auto-vac-${colab.id}-${vac.id}`,
              title: `Limite Concessivo de Férias: ${colabName}`,
              description: `Prazo final para concessão do período aquisitivo (${vac.startDate} a ${vac.endDate}). Evitar pagamento da dobra legal CLT (Art. 137).`,
              date: vac.limitConcessionDate,
              category: 'FERIAS',
              priority: 'URGENTE',
              status: 'PENDENTE',
              poloId: colab.branchId,
              poloNome: colab.branchName,
              collaboratorId: colab.id,
              collaboratorName: colabName,
              collaboratorRole: colab.positionTitle,
              isAutoGenerated: true,
              sourceType: 'FERIAS_DOBRO',
              alertDaysBefore: 30,
              actionLabel: 'Programar Férias',
              actionModule: 'gestao-pessoas',
              createdAt: vac.endDate
            });
          }
        });
      }

      // d) Aniversários de Nascimento
      if (colab.personalData?.birthDate) {
        const parts = colab.personalData.birthDate.split('-');
        if (parts.length === 3) {
          const month = parts[1];
          const day = parts[2];
          const bdayThisYear = `${currentYear}-${month}-${day}`;
          autoList.push({
            id: `auto-bday-${colab.id}`,
            title: `🎂 Aniversário: ${colabName}`,
            description: `Parabenizar o colaborador! Cargo: ${colab.positionTitle}, Polo: ${colab.branchName}.`,
            date: bdayThisYear,
            category: 'ANIVERSARIO',
            priority: 'BAIXA',
            status: 'PENDENTE',
            poloId: colab.branchId,
            poloNome: colab.branchName,
            collaboratorId: colab.id,
            collaboratorName: colabName,
            collaboratorRole: colab.positionTitle,
            isAutoGenerated: true,
            sourceType: 'ANIVERSARIO_NATALICIO',
            recurrence: 'ANUAL',
            alertDaysBefore: 1,
            actionLabel: 'Enviar Parabéns',
            actionModule: 'gestao-pessoas',
            createdAt: colab.admissionDate
          });
        }
      }

      // e) Aniversário de Empresa / Tempo de Casa
      if (colab.admissionDate) {
        const parts = colab.admissionDate.split('-');
        if (parts.length === 3) {
          const admYear = parseInt(parts[0], 10);
          const month = parts[1];
          const day = parts[2];
          const yearsAtCompany = currentYear - admYear;
          if (yearsAtCompany > 0) {
            const tenureDate = `${currentYear}-${month}-${day}`;
            autoList.push({
              id: `auto-tenure-${colab.id}`,
              title: `🌟 ${yearsAtCompany} Ano${yearsAtCompany > 1 ? 's' : ''} de SCL: ${colabName}`,
              description: `Marco na Jornada Own It! Completando ${yearsAtCompany} ano(s) de dedicação e crescimento.`,
              date: tenureDate,
              category: 'ANIVERSARIO',
              priority: 'MEDIA',
              status: 'PENDENTE',
              poloId: colab.branchId,
              poloNome: colab.branchName,
              collaboratorId: colab.id,
              collaboratorName: colabName,
              collaboratorRole: colab.positionTitle,
              isAutoGenerated: true,
              sourceType: 'ANIVERSARIO_EMPRESA',
              recurrence: 'ANUAL',
              alertDaysBefore: 3,
              actionLabel: 'Ver Jornada Own It',
              actionModule: 'gestao-pessoas',
              createdAt: colab.admissionDate
            });
          }
        }
      }
    });
  } catch (err) {
    console.warn('[Lembretes] Erro ao carregar colaboradores:', err);
  }

  // 3. Rotinas Mensais Recorrentes da Folha de Pagamento & DP (12 meses do ano)
  for (let m = 1; m <= 12; m++) {
    const monthStr = m.toString().padStart(2, '0');

    // Fechamento da Folha & Envio ao Contador (Todo dia 25)
    autoList.push({
      id: `auto-folha-fechamento-${currentYear}-${monthStr}`,
      title: `📊 Fechamento da Folha de Pagamento (${monthStr}/${currentYear})`,
      description: `Dia 25: Prazo limite para conferência de ponto, envio de eventos, adicionais e apuração proporcional para a contabilidade.`,
      date: `${currentYear}-${monthStr}-25`,
      category: 'FOLHA_DP',
      priority: 'URGENTE',
      status: 'PENDENTE',
      isAutoGenerated: true,
      sourceType: 'FECHAMENTO_FOLHA',
      recurrence: 'MENSAL',
      alertDaysBefore: 5,
      actionLabel: 'Ir para Preparação da Folha',
      actionModule: 'departamento-pessoal',
      createdAt: `${currentYear}-01-01`
    });

    // Adiantamento Salarial / Vale (Todo dia 20)
    autoList.push({
      id: `auto-folha-adiantamento-${currentYear}-${monthStr}`,
      title: `💳 Adiantamento Salarial / Vale (${monthStr}/${currentYear})`,
      description: `Pagamento do adiantamento quinzenal (40% do salário) para colaboradores optantes.`,
      date: `${currentYear}-${monthStr}-20`,
      category: 'FOLHA_DP',
      priority: 'MEDIA',
      status: 'PENDENTE',
      isAutoGenerated: true,
      sourceType: 'ADIANTAMENTO',
      recurrence: 'MENSAL',
      alertDaysBefore: 2,
      actionLabel: 'Ver DP & Benefícios',
      actionModule: 'departamento-pessoal',
      createdAt: `${currentYear}-01-01`
    });

    // Pagamento Salarial Oficial (5º dia útil - aproximado como dia 05 ou 07)
    autoList.push({
      id: `auto-folha-pagamento-${currentYear}-${monthStr}`,
      title: `💰 Pagamento Salarial (5º Dia Útil - ${monthStr}/${currentYear})`,
      description: `Crédito dos salários integrais nas contas dos colaboradores conforme legislação CLT.`,
      date: `${currentYear}-${monthStr}-05`,
      category: 'FOLHA_DP',
      priority: 'ALTA',
      status: 'PENDENTE',
      isAutoGenerated: true,
      sourceType: 'PAGAMENTO_SALARIO',
      recurrence: 'MENSAL',
      alertDaysBefore: 2,
      actionLabel: 'Conferir Holerites',
      actionModule: 'departamento-pessoal',
      createdAt: `${currentYear}-01-01`
    });
  }

  // 4. Obrigações Especiais de Fim de Ano (13º Salário)
  autoList.push({
    id: `auto-13-primeira-parcela-${currentYear}`,
    title: `🎁 1ª Parcela do 13º Salário (${currentYear})`,
    description: `Prazo final legal para pagamento da primeira parcela do 13º salário (50% sem descontos).`,
    date: `${currentYear}-11-30`,
    category: 'FOLHA_DP',
    priority: 'URGENTE',
    status: 'PENDENTE',
    isAutoGenerated: true,
    sourceType: 'DECIMO_TERCEIRO',
    recurrence: 'ANUAL',
    alertDaysBefore: 7,
    actionLabel: 'Ver Folha 13º',
    actionModule: 'departamento-pessoal',
    createdAt: `${currentYear}-01-01`
  });

  autoList.push({
    id: `auto-13-segunda-parcela-${currentYear}`,
    title: `🎁 2ª Parcela do 13º Salário (${currentYear})`,
    description: `Prazo final legal para pagamento da segunda parcela do 13º salário (com descontos de INSS e IRRF).`,
    date: `${currentYear}-12-20`,
    category: 'FOLHA_DP',
    priority: 'URGENTE',
    status: 'PENDENTE',
    isAutoGenerated: true,
    sourceType: 'DECIMO_TERCEIRO',
    recurrence: 'ANUAL',
    alertDaysBefore: 5,
    actionLabel: 'Ver Folha 13º',
    actionModule: 'departamento-pessoal',
    createdAt: `${currentYear}-01-01`
  });

  return autoList;
}

/**
 * Retorna todos os lembretes combinando eventos automáticos e personalizados do usuário,
 * aplicando os overrides de status/adiamento.
 */
export function getAllLembretes(): LembreteItem[] {
  const autoList = generateAutoLembretes();
  const customList = safeGetJSON<LembreteItem[]>(LEMBRETES_CUSTOM_KEY, []);
  const statusOverrides = safeGetJSON<Record<string, StoredStatusOverride>>(LEMBRETES_STATUS_KEY, {});

  const all = [...autoList, ...customList].map((item) => {
    const override = statusOverrides[item.id];
    if (override) {
      return {
        ...item,
        status: override.status,
        completedAt: override.completedAt || item.completedAt,
        snoozedUntil: override.snoozedUntil || item.snoozedUntil
      };
    }
    return item;
  });

  // Ordena por data ascendente
  return all.sort((a, b) => a.date.localeCompare(b.date));
}

/**
 * Hook reativo para consumo de lembretes na aplicação
 */
export function useStoredLembretes() {
  const [lembretes, setLembretes] = useState<LembreteItem[]>(() => getAllLembretes());

  const refresh = useCallback(() => {
    setLembretes(getAllLembretes());
  }, []);

  useEffect(() => {
    const handler = () => refresh();
    window.addEventListener(LEMBRETES_UPDATE_EVENT, handler);
    window.addEventListener('storage', handler);
    return () => {
      window.removeEventListener(LEMBRETES_UPDATE_EVENT, handler);
      window.removeEventListener('storage', handler);
    };
  }, [refresh]);

  const dispatchUpdate = () => {
    refresh();
    if (typeof window !== 'undefined') {
      window.dispatchEvent(new CustomEvent(LEMBRETES_UPDATE_EVENT));
    }
  };

  const addCustomLembrete = (data: Omit<LembreteItem, 'id' | 'createdAt' | 'isAutoGenerated' | 'sourceType'>): LembreteItem => {
    const customList = safeGetJSON<LembreteItem[]>(LEMBRETES_CUSTOM_KEY, []);
    const newItem: LembreteItem = {
      ...data,
      id: `custom-${Date.now()}-${Math.random().toString(36).substr(2, 5)}`,
      isAutoGenerated: false,
      sourceType: 'CUSTOM',
      createdAt: new Date().toISOString()
    };
    customList.push(newItem);
    safeSetJSON(LEMBRETES_CUSTOM_KEY, customList);
    dispatchUpdate();
    return newItem;
  };

  const updateCustomLembrete = (id: string, data: Partial<LembreteItem>) => {
    const customList = safeGetJSON<LembreteItem[]>(LEMBRETES_CUSTOM_KEY, []);
    const idx = customList.findIndex(i => i.id === id);
    if (idx >= 0) {
      customList[idx] = { ...customList[idx], ...data };
      safeSetJSON(LEMBRETES_CUSTOM_KEY, customList);
      dispatchUpdate();
    }
  };

  const deleteCustomLembrete = (id: string) => {
    const customList = safeGetJSON<LembreteItem[]>(LEMBRETES_CUSTOM_KEY, []);
    const filtered = customList.filter(i => i.id !== id);
    safeSetJSON(LEMBRETES_CUSTOM_KEY, filtered);
    
    // Limpa override se houver
    const overrides = safeGetJSON<Record<string, StoredStatusOverride>>(LEMBRETES_STATUS_KEY, {});
    delete overrides[id];
    safeSetJSON(LEMBRETES_STATUS_KEY, overrides);

    dispatchUpdate();
  };

  const toggleLembreteStatus = (id: string, newStatus?: 'PENDENTE' | 'CONCLUIDO') => {
    const overrides = safeGetJSON<Record<string, StoredStatusOverride>>(LEMBRETES_STATUS_KEY, {});
    const current = overrides[id]?.status || lembretes.find(l => l.id === id)?.status || 'PENDENTE';
    const targetStatus = newStatus || (current === 'CONCLUIDO' ? 'PENDENTE' : 'CONCLUIDO');

    overrides[id] = {
      ...overrides[id],
      status: targetStatus,
      completedAt: targetStatus === 'CONCLUIDO' ? new Date().toISOString() : undefined
    };

    safeSetJSON(LEMBRETES_STATUS_KEY, overrides);
    dispatchUpdate();
  };

  const snoozeLembrete = (id: string, daysToAdd: number = 2) => {
    const overrides = safeGetJSON<Record<string, StoredStatusOverride>>(LEMBRETES_STATUS_KEY, {});
    const today = new Date();
    today.setDate(today.getDate() + daysToAdd);
    const snoozedDate = today.toISOString().split('T')[0];

    overrides[id] = {
      ...overrides[id],
      status: 'ADIADO',
      snoozedUntil: snoozedDate
    };

    safeSetJSON(LEMBRETES_STATUS_KEY, overrides);
    dispatchUpdate();
  };

  return {
    lembretes,
    refresh,
    addCustomLembrete,
    updateCustomLembrete,
    deleteCustomLembrete,
    toggleLembreteStatus,
    snoozeLembrete
  };
}

/**
 * Retorna os alertas que requerem atenção iminente
 * (eventos pendentes cuja data é hoje ou nos próximos X dias, ou que estão em atraso de até 7 dias)
 */
export function getImminentAlerts(daysAhead: number = 7): LembreteItem[] {
  const all = getAllLembretes();
  const todayStr = new Date().toISOString().split('T')[0];

  return all.filter((item) => {
    if (item.status === 'CONCLUIDO') return false;

    // Se foi adiado para uma data futura, respeita o adiamento
    if (item.status === 'ADIADO' && item.snoozedUntil && item.snoozedUntil > todayStr) {
      return false;
    }

    const diff = getDaysDifference(item.date);
    // Dispara se estiver atrasado (até -7 dias) ou se estiver dentro do raio de alerta definido
    const triggerWindow = Math.max(item.alertDaysBefore || 3, daysAhead);
    return diff >= -7 && diff <= triggerWindow;
  }).sort((a, b) => {
    // Prioriza Urgentes e menor diferença de dias
    const priorityWeight: Record<LembretePriority, number> = {
      URGENTE: 4,
      ALTA: 3,
      MEDIA: 2,
      BAIXA: 1
    };
    if (priorityWeight[a.priority] !== priorityWeight[b.priority]) {
      return priorityWeight[b.priority] - priorityWeight[a.priority];
    }
    return a.date.localeCompare(b.date);
  });
}

/**
 * Controle de exibição do pop-up para não incomodar o usuário na mesma sessão
 */
export function isPopupDismissedForToday(): boolean {
  if (typeof window === 'undefined') return false;
  try {
    const dismissedDate = localStorage.getItem(LEMBRETES_POPUP_DISMISSED_KEY);
    const todayStr = new Date().toISOString().split('T')[0];
    return dismissedDate === todayStr;
  } catch {
    return false;
  }
}

export function dismissPopupForToday(): void {
  if (typeof window === 'undefined') return;
  try {
    const todayStr = new Date().toISOString().split('T')[0];
    localStorage.setItem(LEMBRETES_POPUP_DISMISSED_KEY, todayStr);
  } catch (err) {
    console.warn('[LembretesStorage] Erro ao gravar dismiss:', err);
  }
}
